### ISSUE TITLE
Parsing Error while reading the config file

### ISSUE THREAD

**Issue by TekyaygilFethi** [surajsubramanian/EmotionDetection#1]
Hello,
I'm encountering with the error while execution of code block below:
`net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)`
The error is:
`net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:210: error: (-212:Parsing error) Failed to open NetParameter file: C:\Users\VİCTUS\Desktop\GithubRepositories\EmotionDetection\yolo_predictor\cfg\yolov3-custom.cfg in function 'cv::dnn::dnn4_v20220524::readNetFromDarknet'`

I'm giving abolute paths as shown:
`configPath = r"C:\Users\VİCTUS\Desktop\GithubRepositories\EmotionDetection\yolo_predictor\cfg\yolov3-custom.cfg"`

`weightsPath = r"C:\Users\VİCTUS\Desktop\GithubRepositories\EmotionDetection\yolo_predictor\yolov3-custom_9700.weights"`

Any help will be appreciated.

**Comment by surajsubramanian** [comment]
Hey mate! 
The error seems to be in the package at first glance. Also possible that it's because this repository is quite old and the packages used might be outdated. 
I won't be able to assist you, for now. Hope you can understand. Good luck!
Apologies, Suraj.

**Comment by surajsubramanian** [comment]
Hello, I've checked my code and it works well. Usage of absolute paths was never recommended, files were asked to be downloaded from the gdrive links and dropped into root and yolo-predictor directories if you can read the README again(under Usage).

I'd suggest you try the updated code again, regardless I'll set up docker for this repository soon if time permits.
